apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: certificate-operator-tests
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  pipelineSpec:
    params:
      - name: repo-url
        type: string
      - name: revision
        type: string
    workspaces:
      - name: source
    tasks:
      - name: run-tests
        taskRef:
          name: run-tests
        params:
          - name: repo-url
            value: $(params.repo-url)
          - name: revision
            value: $(params.revision)
        workspaces:
          - name: source
            workspace: source
  params:
    - name: repo-url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
